package model

import "github.com/mmedum/google-mail-mcp/internal/mime"

// The results of writes. Each says the state the write produced, read
// from Gmail's answer rather than assumed from the request (§4.12), and
// a dry run says what would have been done.

// Origin is where a draft's recipient came from.
type Origin string

// Recipient origins.
const (
	// FromCaller is an address the caller named.
	FromCaller Origin = "caller"
	// FromParent is the replied-to message's sender, or its Reply-To.
	FromParent Origin = "parent"
	// FromReplyAll is one of the replied-to message's other recipients.
	FromReplyAll Origin = "reply_all"
	// FromDraft is an address the draft already had and still has.
	FromDraft Origin = "draft"
)

// Recipient is one address a draft is going to.
type Recipient struct {
	Address mime.Address
	// Field is "to", "cc" or "bcc".
	Field  string
	Origin Origin
}

// File is an attachment of a draft.
type File struct {
	// Name is what the recipient sees. From a file in GMAIL_LOCAL_DIR,
	// whose name may have come from a sender, or from the draft.
	Name      Untrusted
	MediaType Untrusted
	Size      int
	// PartID names it in the draft, when it is already there.
	PartID string
}

// Reply is how a draft answers another message (§4.5).
type Reply struct {
	ParentID       string
	ParentThreadID string
	// FromThread is set when the parent was chosen as the newest
	// message of a thread the caller named.
	FromThread bool
	// Joined reports whether Gmail filed the draft in the parent's
	// thread, read from its answer. False on a dry run.
	Joined bool
	// NoMessageID is set when the parent carries no usable Message-ID,
	// so In-Reply-To and References could not be written.
	NoMessageID bool
	ReplyAll    bool
	// DroppedOwn counts the account's own addresses left out.
	DroppedOwn int
	// Unwritable counts the parent's addresses left out because they
	// cannot be written into a header: not ASCII local@domain.
	Unwritable int
}

// DraftWrite is a created, updated or deleted draft.
type DraftWrite struct {
	// Op is "create", "update" or "delete".
	Op     string
	DryRun bool

	DraftID string
	// MessageID is the id of the message inside the draft now: after a
	// create or update, the witness the next update_draft needs. For a
	// delete, the message that was deleted.
	MessageID string
	// PreviousMessageID is the witness an update was checked against.
	PreviousMessageID string
	ThreadID          string
	Labels            []LabelRef

	From       *mime.Address
	Recipients []Recipient
	Subject    Untrusted
	// RFC822MessageID is the Message-ID header, generated by this server
	// for a draft it created.
	RFC822MessageID Untrusted
	Files           []File
	Added, Removed  []File
	// Changed names the fields an update changed.
	Changed []string
	Reply   *Reply
	// Bytes is the size of the message sent to Gmail, and Upload whether
	// it went as a media upload (§7.4).
	Bytes  int
	Upload bool
	// ThreadingAtRisk is set when an update changed the subject of a
	// reply, one of the three things Gmail threads by (§2.5).
	ThreadingAtRisk bool
	// Gone is set when Gmail answered a delete with 404 after the draft
	// had been read: it was deleted, by this call's earlier attempt or
	// elsewhere.
	Gone bool
}

// ItemKind is what an id in a multi-id write names.
type ItemKind string

// Item kinds.
const (
	KindMessage ItemKind = "message"
	KindThread  ItemKind = "thread"
)

// Outcome is what a write did to one item (§4.7).
type Outcome string

// Outcomes.
const (
	Changed     Outcome = "changed"
	Unchanged   Outcome = "unchanged"
	WouldChange Outcome = "would_change"
	Failed      Outcome = "failed"
)

// Item is one message or thread of a multi-id write.
type Item struct {
	ID      string
	Kind    ItemKind
	Outcome Outcome
	// Class and Error say why it failed: a class of §6.5 and the
	// server's message, which carries no mail content.
	Class, Error string
	// Before and After are its labels; for a thread, the union over its
	// messages.
	Before, After []LabelRef
}

// ItemsWrite is modify_labels, trash, restore or delete_permanently
// over many ids. For delete_permanently, Changed means deleted for good.
type ItemsWrite struct {
	// Op is "modify_labels", "trash", "restore" or "delete_permanently".
	Op     string
	DryRun bool
	// Add and Remove are the labels asked for, resolved.
	Add, Remove []LabelRef
	// Verbs name what the change amounts to: archive, mark read, star.
	Verbs []string
	Items []Item
}

// Count is how many items had an outcome.
func (w ItemsWrite) Count(o Outcome) int {
	n := 0
	for _, it := range w.Items {
		if it.Outcome == o {
			n++
		}
	}
	return n
}

// LabelWrite is a created, updated or deleted label.
type LabelWrite struct {
	// Op is "create", "update" or "delete".
	Op     string
	DryRun bool
	// Before is the label as it was, for an update or a delete; a
	// delete's carries its counts.
	Before *Label
	// After is the label Gmail answered with, or would be. Zero for a
	// delete.
	After Label
	// Changed names the fields an update changed.
	Changed []string
	// Gone is set when Gmail answered a delete that the label was
	// already gone, after it had been read.
	Gone bool
}

// LabelListWords are this server's words for a label's place in Gmail's
// label list, and the API's spelling of each. The tools take and show
// the words; only the wire carries labelShow and its kin.
var LabelListWords = map[string]string{"show": "labelShow", "show_if_unread": "labelShowIfUnread", "hide": "labelHide"}

// MessageListWords are the words for whether a label shows on messages
// in a listing; they are the API's own.
var MessageListWords = map[string]string{"show": "show", "hide": "hide"}

// InLabelList is the label's labelListVisibility in this server's words,
// or "" when Gmail did not say.
func (l Label) InLabelList() string {
	for word, api := range LabelListWords {
		if api == l.LabelListVisibility {
			return word
		}
	}
	return ""
}

// Verb is what a label change amounts to in Gmail's own words (§7.5):
// adding or removing Label is Name.
type Verb struct {
	Label string
	Add   bool
	Name  string
}

// Verbs are every verb modify_labels names.
var Verbs = []Verb{
	{"INBOX", false, "archive"}, {"INBOX", true, "move to the inbox"},
	{"UNREAD", false, "mark read"}, {"UNREAD", true, "mark unread"},
	{"STARRED", true, "star"}, {"STARRED", false, "unstar"},
	{"IMPORTANT", true, "mark important"}, {"IMPORTANT", false, "mark not important"},
	{"SPAM", true, "report spam"}, {"SPAM", false, "not spam"},
}

// DraftFields are the fields an update_draft can change, as Changed
// names them; LabelFields are update_label's.
var (
	DraftFields = []string{"to", "cc", "bcc", "subject", "body", "body_html", "attachments"}
	LabelFields = []string{"name", "in_label_list", "in_message_list", "color"}
)

// SendRecipient is one address a draft is sent to, and how the recipient
// guard of §4.2 judged it.
type SendRecipient struct {
	Address mime.Address
	// Field is "to", "cc" or "bcc", and Position its place there from 0:
	// the guard names it Field[Position].
	Field    string
	Position int
	// Participant is set when the address is on a message of the thread
	// the draft answers, so it needs no confirmation.
	Participant bool
	// Confirmed is set when confirm_recipients names it.
	Confirmed bool
}

// Cleared reports whether the guard lets this recipient through.
func (r SendRecipient) Cleared() bool { return r.Participant || r.Confirmed }

// SendWrite is a sent draft, or what a dry run would send (§4.2).
type SendWrite struct {
	DryRun  bool
	DraftID string
	// MessageID is the message inside the draft, read before the send:
	// the witness the call was checked against.
	MessageID string
	ThreadID  string
	// Answers counts the thread's messages the draft answers: those that
	// are not drafts, spam or trash. Zero is a new conversation, where
	// every recipient needs confirming.
	Answers int

	From            *mime.Address
	Recipients      []SendRecipient
	Subject         Untrusted
	RFC822MessageID Untrusted
	Files           []File

	// SentID, SentThreadID and SentLabels are Gmail's answer to the send.
	SentID       string
	SentThreadID string
	SentLabels   []LabelRef
}

// Unconfirmed counts the recipients the guard stops.
func (s SendWrite) Unconfirmed() int {
	n := 0
	for _, r := range s.Recipients {
		if !r.Cleared() {
			n++
		}
	}
	return n
}

// Settled is what the reads after an ambiguous send found (§4.3).
type Settled string

// Verdicts.
const (
	// SettledSent: the draft is gone and its Message-ID is in SENT.
	SettledSent Settled = "sent"
	// SettledNotSent: the draft is still there and nothing carrying its
	// Message-ID is in SENT.
	SettledNotSent Settled = "not_sent"
	// SettledUnknown: anything else, including a read that failed.
	SettledUnknown Settled = "unknown"
)
