package main

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
)

// launcherScript is the Linux launcher, generated from the staging
// table so its binary names cannot drift from the packer's.
//
// A manifest names a command per platform and has no key for the
// architecture, and Linux has no universal binary, so the launcher picks
// one by `uname -m` and execs it: the server speaks MCP over this
// process's stdio, and a shell left in the middle would own the pipes.
// Every message goes to stderr, because a line on stdout corrupts the
// JSON-RPC stream before the client's first request completes.
func launcherScript(files []mcpbStaged) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n" +
		"# Generated by `gates mcpb-pack` from its staging table. Do not edit.\n" +
		"set -eu\n\n" +
		`dir=$(dirname "$0")` + "\n\n" +
		`case "$(uname -m)" in` + "\n")
	for _, f := range files {
		if len(f.uname) == 0 {
			continue
		}
		_, _ = fmt.Fprintf(&b, "  %s)\n    bin=\"$dir/%s\"\n    ;;\n", strings.Join(f.uname, " | "), filepath.Base(f.path))
	}
	b.WriteString("  *)\n" +
		`    echo "` + binaryName + `: no binary in this bundle for $(uname -m); builds for x86_64 and aarch64 ` +
		`are at https://github.com/mmedum/` + binaryName + `/releases" >&2` + "\n" +
		"    exit 1\n    ;;\nesac\n\n" +
		`if [ ! -x "$bin" ]; then` + "\n" +
		`  echo "` + binaryName + `: $bin is missing from the bundle or not executable; reinstall the bundle" >&2` + "\n" +
		"  exit 1\nfi\n\n" +
		`exec "$bin" "$@"` + "\n")
	return b.String()
}

// launcherBinary matches a binary the launcher chooses.
var launcherBinary = regexp.MustCompile(`bin="\$dir/([A-Za-z0-9._-]+)"`)

// launcherNamesIn reads the names back out of a generated script, so the
// gate compares the script with the table rather than the table with
// itself: a generator that skipped a row fails.
func launcherNamesIn(body string) []string {
	matches := launcherBinary.FindAllStringSubmatch(body, -1)
	out := make([]string, 0, len(matches))
	for _, m := range matches {
		out = append(out, m[1])
	}
	return out
}
